# Generated by Django 6.0.2 on 2026-03-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('restaurant_id', models.CharField(max_length=50)),
                ('restaurant_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('guests', models.PositiveIntegerField()),
                ('card_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
