# Generated by Django 6.0.2 on 2026-03-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='card_url',
        ),
        migrations.AddField(
            model_name='booking',
            name='card_image_data_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_code_data_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
