# Generated by Django 6.0.2 on 2026-03-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_card_url_booking_card_image_data_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='Customer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='Customer', max_length=20),
            preserve_default=False,
        ),
    ]
