# Generated by Django 6.0.2 on 2026-03-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='card_image_data_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='qr_code_data_url',
            field=models.TextField(blank=True),
        ),
    ]
